import os
from docx import Document

def create_structured_docx(filename: str, title: str, sections: dict) -> str:
    """Generates a clean, structured Word document from a dictionary of sections."""
    doc = Document()
    
    # Document Header
    doc.add_heading(title, level=0)
    
    # Dynamically inject sections generated by the agent
    for section_title, content in sections.items():
        doc.add_heading(section_title, level=1)
        doc.add_paragraph(content)
        
    # Ensure output directory exists safely
    output_dir = "output"
    os.makedirs(output_dir, exist_ok=True)
    
    file_path = os.path.join(output_dir, f"{filename}.docx")
    doc.save(file_path)
    return file_path